# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoStarknet < Formula
  desc ""
  homepage "https://github.com/dontpanicdao/caigo"
  version "0.4.1-beta1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dontpanicdao/caigo/releases/download/v0.4.1-beta1/go-starknet_0.4.1-beta1_darwin_x86_64.tar.gz"
      sha256 "3bd145abe7fc2d9a446ae8825519c39f24a2930758c58509871a15744536a93a"

      def install
        bin.install "go-starknet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dontpanicdao/caigo/releases/download/v0.4.1-beta1/go-starknet_0.4.1-beta1_darwin_arm64.tar.gz"
      sha256 "d68eb20268d446eb4e5165088087b354e49426a748f4cfbd46f382fa9ff8cd73"

      def install
        bin.install "go-starknet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dontpanicdao/caigo/releases/download/v0.4.1-beta1/go-starknet_0.4.1-beta1_linux_arm64.tar.gz"
      sha256 "9e1f462b368252db6f4892d3f7785a0c39ac54450ef32925d8b05a5ede742ca0"

      def install
        bin.install "go-starknet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dontpanicdao/caigo/releases/download/v0.4.1-beta1/go-starknet_0.4.1-beta1_linux_x86_64.tar.gz"
      sha256 "28592ca89c50abf2d27fb041a2fe19899de025bf9fd398c9b33c56bd22a55d3f"

      def install
        bin.install "go-starknet"
      end
    end
  end
end
